name: Prod CI/CD (Build & Deploy)

on:
   # Trigger the workflow on push or pull request,
  # but only for the master branch!
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install node 12.x & npm
      uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '12.x'
    - name: cache node_modules
      uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-    
    - name: npm install
      run:
        npm install
    - name: npm run-script build
      run: 
        npm run-script build
    # - name: Test
    #   run: |
    #     npm test
    - name: archive build
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: deployable_artifacts
        path: dist
    # - name: Archive code coverage result
    #   if: success()
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: deploy_coverage
    #     path: coverage

  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: checkout
          uses: actions/checkout@v1
        - name: download build artifacts
          uses: actions/download-artifact@v1
          with:
            name: deployable_artifacts
        - name: deploy to github pages
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: deployable_artifacts
     
