# This is a basic workflow to help you get started with Actions
name: CI/CD (Build & Deploy)

# Controls when the action will run.
on:
  # Trigger the workflow on push or pull request, but only for the selected branch below!
  push:
    branches: [master]
    # branches: [master, dev/*]
  pull_request:
    branches: [master]
    # branches: [master, dev/*]
    paths-ignore:
      - '**/README.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout master branch
      uses: actions/checkout@v2

    - name: Install Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    # This allows for re-using node_modules caching, making builds a bit faster.
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install latest NPM
      run: npm i -g npm@latest

    - name: Install packages
      run: npm install

    - name: Run Tests
      run: npm run-script test:headless

    # Need them as zip in terms of some usage
    - name: Archive code coverage result
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: code_coverage_artifacts
        path: coverage

    - name: Upload code coverage to Codecov
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

    - name: Run build script
      run: npm run-script build
      env:
        IS4_BAIGANIO_CLIENT_SECRET: ${{ secrets.IS4_BAIGANIO_CLIENT_SECRET }}
        IS4_BAIGANIO_USER_SECRET: ${{ secrets.IS4_BAIGANIO_USER_SECRET }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    - name: Archive and upload build artifacts
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: deployable_artifacts
        path: dist

  # This workflow contains a second job called "deploy"
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout repo
          uses: actions/checkout@v1

        - name: Download build artifacts
          uses: actions/download-artifact@v1
          with:
            name: deployable_artifacts

        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: deployable_artifacts
          env:
            IS4_BAIGANIO_CLIENT_SECRET: ${{ secrets.IS4_BAIGANIO_CLIENT_SECRET }}
            IS4_BAIGANIO_USER_SECRET: ${{ secrets.IS4_BAIGANIO_USER_SECRET }}
            YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
