name: Reusable [Build & Upload artifacts] workflow

on:
  workflow_call:

jobs:
  deploy:
    name: Build & Upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v1

      - name: Run build script
        run: npm run-script build
        env:
          IS4_BAIGANIO_CLIENT_SECRET: ${{ secrets.IS4_BAIGANIO_CLIENT_SECRET }}
          IS4_BAIGANIO_USER_SECRET: ${{ secrets.IS4_BAIGANIO_USER_SECRET }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Archive and upload build artifacts
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deployable_artifacts
          path: dist
