name: Reusable [Upload code coverage to Codecov] workflow

on:
  workflow_call:

jobs:
  upload:
    name: Upload code coverage to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Upload code coverage to Codecov
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
