name: Reusable [Download & Deploy artifacts to GitHub Pages] workflow

on:
  workflow_call:

jobs:
  download-and-deploy:
    name: Download & Deploy artifacts to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: deployable_artifacts

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deployable_artifacts
        env:
          IS4_BAIGANIO_CLIENT_SECRET: ${{ secrets.IS4_BAIGANIO_CLIENT_SECRET }}
          IS4_BAIGANIO_USER_SECRET: ${{ secrets.IS4_BAIGANIO_USER_SECRET }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
